# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://ep-floral-mode-admt1vb3.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6TkjpXcRe0dl
spring.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ⛔ THIS IS CRITICAL
spring.jpa.defer-datasource-initialization=true

# ================= SQL INIT =================
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.data-locations=classpath:database-setup.sql

# ⛔ FORCE execution even if tables exist
spring.sql.init.continue-on-error=true

# ================= HIKARI (Neon-safe) =================
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=10000
logging.level.org.springframework.boot.context.config=DEBUG

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG


